Fix/basket
oleksandr-bratashchuk/react_marketplace_app pull request #5
Opened 2022-06-02 08:44 UTC by oleksandr-bratashchuk

2022-06-02 08:46 UTC, oleksandr-bratashchuk commented on src/api/products.ts
> +  console.log(data);
@oleksandr-bratashchuk remove console.log()

2022-06-02 09:18 UTC, Bohdan-ya requested changes

2022-06-02 09:18 UTC, Bohdan-ya commented on src/components/ProductForm/ProductForm.tsx
> +  React.useEffect(() => {
@oleksandr-bratashchuk use useMemo instead useState and useEffect

2022-06-02 09:18 UTC, Bohdan-ya commented on src/components/ProductForm/ProductForm.tsx
> +      initialValues={
@oleksandr-bratashchuk add separate object for this , and use it instead

2022-06-02 09:18 UTC, Bohdan-ya commented on src/components/ProductForm/ProductForm.tsx
> +      validationSchema={Yup.object().shape({
@oleksandr-bratashchuk the same

2022-06-02 09:18 UTC, Bohdan-ya commented on src/components/ProductForm/ProductForm.tsx
> +      onSubmit={async (values, { setSubmitting }) => {
@oleksandr-bratashchuk the same. Add function for this

2022-06-02 09:18 UTC, Bohdan-ya commented on src/contexts/SearchContext.tsx
>    const [query, setQuery] = React.useState('');
@oleksandr-bratashchuk use/or not use generics

2022-06-02 09:18 UTC, Bohdan-ya commented on src/types/models/BasketData.ts
> +  id: number;
@oleksandr-bratashchuk check it

2022-06-03 08:23 UTC, Bohdan-ya approved these changes

2022-06-03 08:24 UTC, merged